apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblens
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weblens
  template:
    metadata:
      labels:
        app: weblens
    spec:
      containers:
      - name: weblens
        image: guardianlux/iweblens-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30001
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: weblens-entry
  namespace: default
spec:
  type: NodePort
  selector:
    app: weblens
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001

            