apiVersion: v1
kind: Service
metadata:
  name: iweblens-server
  namespace: iweblens
spec:
  selector:
    app: iweblens-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort